version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/notebook
    binary: notebook
    ldflags:
      - -s -w -X github.com/oobagi/notebook-cli/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: oobagi
    name: notebook-cli
